
/* MSG_publisher.cxx

A publication of data of type myStruct

This file is derived from code automatically generated by the rtiddsgen 
command:

rtiddsgen -language C++ -example <arch> MSG.idl

Example publication of type myStruct automatically generated by 
'rtiddsgen'. To test them follow these steps:

(1) Compile this file and the example subscription.

(2) Start the subscription with the command
objs/<arch>/MSG_subscriber <domain_id> <sample_count>

(3) Start the publication with the command
objs/<arch>/MSG_publisher <domain_id> <sample_count>

(4) [Optional] Specify the list of discovery initial peers and 
multicast receive addresses via an environment variable or a file 
(in the current working directory) called NDDS_DISCOVERY_PEERS. 

You can run any number of publishers and subscribers programs, and can 
add and remove them dynamically from the domain.

Example:

To run the example application on domain <domain_id>:

On Unix: 

objs/<arch>/MSG_publisher <domain_id> o
objs/<arch>/MSG_subscriber <domain_id> 

On Windows:

objs\<arch>\MSG_publisher <domain_id>  
objs\<arch>\MSG_subscriber <domain_id>    

*/

#include <stdio.h>
#include <stdlib.h>

#include "MSG.h"
#include "MSGSupport.h"
#include "ndds/ndds_cpp.h"

#include <iostream>

using namespace std;

/* Delete all entities */
static int publisher_shutdown(
    DDSDomainParticipant *participant)
{
    DDS_ReturnCode_t retcode;
    int status = 0;

    if (participant != NULL) {
        retcode = participant->delete_contained_entities();
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_contained_entities error %d\n", retcode);
            status = -1;
        }

        retcode = DDSTheParticipantFactory->delete_participant(participant);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "delete_participant error %d\n", retcode);
            status = -1;
        }
    }

    /* RTI Connext provides finalize_instance() method on
    domain participant factory for people who want to release memory used
    by the participant factory. Uncomment the following block of code for
    clean destruction of the singleton. */
    /*

    retcode = DDSDomainParticipantFactory::finalize_instance();
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "finalize_instance error %d\n", retcode);
        status = -1;
    }
    */

    return status;
}

void SetPartitionQoS(const char* tag, DDSPublisher* publisher)
{
	DDS_PublisherQos publisher_qos;
	publisher->get_qos(publisher_qos);
	cout << publisher_qos.partition.name.length() << "," << publisher_qos.partition.name.maximum() << std::endl;
	publisher_qos.partition.name.length(1);
	publisher_qos.partition.name[0] = DDS_String_dup(tag);
	cout << publisher_qos.partition.name.length() << "," << publisher_qos.partition.name.maximum() << std::endl;
	publisher->set_qos(publisher_qos);
}


extern "C" int publisher_main(int domainId, int sample_count)
{
    DDSDomainParticipant *participant = NULL;
    DDSPublisher *publisher = NULL;
    DDSTopic *topic = NULL;
    DDSDataWriter *writer = NULL;
    myStructDataWriter * myStruct_writer = NULL;
    myStruct *instance = NULL;
    DDS_ReturnCode_t retcode;
    DDS_InstanceHandle_t instance_handle = DDS_HANDLE_NIL;
    const char *type_name = NULL;
    int count = 0;  
    DDS_Duration_t send_period = {4,0};

    /* To customize participant QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    participant = DDSTheParticipantFactory->create_participant(
        domainId, DDS_PARTICIPANT_QOS_DEFAULT, 
        NULL /* listener */, DDS_STATUS_MASK_NONE);
    if (participant == NULL) {
        fprintf(stderr, "create_participant error\n");
        publisher_shutdown(participant);
        return -1;
    }

	DDS_PublisherQos DefPubQOS;
	participant->get_default_publisher_qos(DefPubQOS);
	DefPubQOS.partition.name.maximum(3);
	DefPubQOS.partition.name.length(1);
	DefPubQOS.partition.name[0] = "*";
	//DefPubQOS.publisher_name.name = "HELLO";
	cout << DefPubQOS.partition.name.length() << "," << DefPubQOS.partition.name.maximum() << std::endl;

    /* To customize publisher QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    publisher = participant->create_publisher(
		DefPubQOS, NULL /* listener */, DDS_STATUS_MASK_NONE);
    if (publisher == NULL) {
        fprintf(stderr, "create_publisher error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* Register type before creating topic */
    type_name = myStructTypeSupport::get_type_name();
    retcode = myStructTypeSupport::register_type(
        participant, type_name);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "register_type error %d\n", retcode);
        publisher_shutdown(participant);
        return -1;
    }

    /* To customize topic QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    topic = participant->create_topic(
        "Example myStruct",
        type_name, DDS_TOPIC_QOS_DEFAULT, NULL /* listener */,
        DDS_STATUS_MASK_NONE);
    if (topic == NULL) {
        fprintf(stderr, "create_topic error\n");
        publisher_shutdown(participant);
        return -1;
    }


	{
		DDS_PublisherQos publisher_qos;
		DDS_ReturnCode_t retcode =  publisher->get_qos(publisher_qos);
		if (retcode != DDS_RETCODE_OK) {
			fprintf(stderr, "register_type error %d\n", retcode);
			publisher_shutdown(participant);
			return -1;
		}
		cout << publisher_qos.partition.name.length() << "," << publisher_qos.partition.name.maximum() << std::endl;
	}

	SetPartitionQoS("EFG", publisher);

    /* To customize data writer QoS, use 
    the configuration file USER_QOS_PROFILES.xml */
    writer = publisher->create_datawriter(
        topic, DDS_DATAWRITER_QOS_DEFAULT, NULL /* listener */,
        DDS_STATUS_MASK_NONE);
    if (writer == NULL) {
        fprintf(stderr, "create_datawriter error\n");
        publisher_shutdown(participant);
        return -1;
    }
    myStruct_writer = myStructDataWriter::narrow(writer);
    if (myStruct_writer == NULL) {
        fprintf(stderr, "DataWriter narrow error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* Create data sample for writing */
    instance = myStructTypeSupport::create_data();
    if (instance == NULL) {
        fprintf(stderr, "myStructTypeSupport::create_data error\n");
        publisher_shutdown(participant);
        return -1;
    }

    /* For a data type that has a key, if the same instance is going to be
    written multiple times, initialize the key here
    and register the keyed instance prior to writing */
    /*
    instance_handle = myStruct_writer->register_instance(*instance);
    */

    /* Main loop */
    for (count=0; (sample_count == 0) || (count < sample_count); ++count) {

        printf("Writing myStruct, count %d\n", count);

        /* Modify the data to be sent here */

        retcode = myStruct_writer->write(*instance, instance_handle);
        if (retcode != DDS_RETCODE_OK) {
            fprintf(stderr, "write error %d\n", retcode);
        }

        NDDSUtility::sleep(send_period);
    }

    /*
    retcode = myStruct_writer->unregister_instance(
        *instance, instance_handle);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "unregister instance error %d\n", retcode);
    }
    */

    /* Delete data sample */
    retcode = myStructTypeSupport::delete_data(instance);
    if (retcode != DDS_RETCODE_OK) {
        fprintf(stderr, "myStructTypeSupport::delete_data error %d\n", retcode);
    }

    /* Delete all entities */
    return publisher_shutdown(participant);
}

int main(int argc, char *argv[])
{
    int domainId = 0;
    int sample_count = 0; /* infinite loop */

    if (argc >= 2) {
        domainId = atoi(argv[1]);
    }
    if (argc >= 3) {
        sample_count = atoi(argv[2]);
    }

    /* Uncomment this to turn on additional logging
    NDDSConfigLogger::get_instance()->
    set_verbosity_by_category(NDDS_CONFIG_LOG_CATEGORY_API, 
    NDDS_CONFIG_LOG_VERBOSITY_STATUS_ALL);
    */

    return publisher_main(domainId, sample_count);
}

